settings:
  username: "WilliamDavidHarrison"
  commit_msg: "Update Recent Activity"
  max_lines: 10
  readme_file: "README.md"
  disabled_events:
    - "member"
    - "push"
    - "wiki"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+0:00"
    text: "###### Last Updated: {DATE}"
    format: "dS mmmm, yyyy @ HH:MMtt Z"
  commit_name: "WDH-Bot"
  commit_email: "bot@williamharrison.dev"
messages:
  comments: "[![comments](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Comment.svg)]({ID}) Commented on {ID} in {REPO}"
  issue_opened: "[![issue_opened](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/IssueOpened.svg)]({ID}) Opened issue {ID} in {REPO}"
  issue_closed: "[![issue_closed](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/IssueClosed.svg)]({ID}) Closed issue {ID} in {REPO}"
  pr_opened: "[![pr_opened](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestOpened.svg)]({ID}) Opened PR {ID} in {REPO}"
  pr_closed: "[![pr_closed](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestClosed.svg)]({ID}) Closed PR {ID} in {REPO}"
  pr_merged: "[![pr_merged](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestMerged.svg)]({ID}) Merged PR {ID} in {REPO}"
  create_repo: "[![create_repo](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Repository.svg)]({REPO}) Created new repository {REPO}"
  fork_repo: "[![fork_repo](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/ForkedRepository.svg)]({FORK}) Forked {FORK} from {REPO}"
  wiki_create: "[![wiki_create](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Wiki.svg)]({WIKI}) Created new wiki page {WIKI} in {REPO}"
  added_member: "[![added_member](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/People.svg)]({REPO}) Became collaborator on {REPO}"
  changes_approved: "[![changes_approved](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/ApprovedChanges.svg)]({ID}) Approved {ID} in {REPO}"
  changes_requested: "[![changes_requested](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/RequestedChanges.svg)]({ID}) Requested changes in {ID} in {REPO}"
  new_release: "[![new_release](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Release.svg)]({ID}) Released {ID} in {REPO}"
  new_star: "[![new_star](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/StarredRepository.svg)]({REPO}) Starred {REPO}"
