settings:
  username: "WilliamDavidHarrison"
  commit_msg: "Update Recent Activity"
  max_lines: 10
  readme_file: "README.md"
  disabled_events:
    - "push"
    - "wiki"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+0:00"
    text: "###### Last Updated: {DATE}"
    format: "dS mmmm, yyyy HH:MMtt Z"
  commit_name: "WDH-Bot"
  commit_email: "bot@williamharrison.dev"
messages:
  comments: "💬 Commented on {ID} in {REPO}"
  issue_opened: "❗️ Opened issue {ID} in {REPO}"
  issue_closed: "✔️ Closed issue {ID} in {REPO}"
  pr_opened: "💪 Opened PR {ID} in {REPO}"
  pr_closed: "❌ Closed PR {ID} in {REPO}"
  pr_merged: "🎉 Merged PR {ID} in {REPO}"
  create_repo: "🆕 Created new repository {REPO}"
  fork_repo: "🔱 Forked {FORK} from {REPO}"
  wiki_create: "📖 Created new wiki page {WIKI} in {REPO}"
  added_member: "🤝 Became collaborator on {REPO}"
  changes_approved: "✅ Approved {ID} in {REPO}"
  changes_requested: "🔴 Requested changes in {ID} in {REPO}"
  new_release: "✌️ Released {ID} in {REPO}"
  new_star: "⭐ Starred {REPO}"
