name: Sponsors

on:
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"
