name: GitHub Stats

on:
    workflow_dispatch: {}

    schedule:
        - cron: "0 * * * *"

defaults:
    run:
        working-directory: github-stats

jobs:
    build:
        name: Update SVG
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - run: cd github-stats

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install Requirements
              run: npm install

            - name: Set Git Config
              run: |
                  git config --global user.name "WDH-Bot"
                  git config --global user.email "bot@williamharrison.dev"
                  git pull

            - name: Update Template
              run: node ./src/updater.js ${{ github.repository_owner }} dracula
              env:
                  BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

            - name: Commit
              run: |
                  git add .
                  git commit -m "Update GitHub Stats SVG" || echo
                  git push
