name: Recent Activity

on:
    workflow_dispatch: {}

    schedule:
        - cron: "0 * * * *"

jobs:
    build:
        name: Update README
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Update Recent Activity
              uses: Readme-Workflows/recent-activity@main
              env:
                  GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
              with:
                  CONFIG_FILE: ".github/recent-activity.yml"
