name: Recent Activity

on:
    workflow_dispatch: {}

    schedule:
        - cron: "0 * * * *"

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: Readme-Workflows/recent-activity@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  CONFIG_FILE: "configs/recent-activity.yml"
