name: Recent Activity

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Recent Activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update Recent Activity"
          MAX_LINES: 5
