name: Sponsors

on:
    schedule:
        - cron: 0 0 * * *

    workflow_dispatch:

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Update Sponsors
              uses: JamesIves/github-sponsors-readme-action@v1
              with:
                  token: ${{ secrets.PAT }}
                  file: "README.md"
                  minimum: "500"
                  fallback: "There are no sponsors 😔"

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: main
                  folder: "."
