name: Wakatime

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Wakatime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Update Wakatime Metrics"
          SHOW_PROFILE_VIEWS: False
          SHOW_SHORT_INFO: False
          SHOW_TOTAL_CODE_TIME: False
